version: '3.9'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${SECRET_DB_USER}
      POSTGRES_PASSWORD: ${SECRET_DB_PASSWORD}
      POSTGRES_DB: ${SECRET_DB_NAME}
    volumes:
      - ./database/pgdata:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d/
    ports:
      - "${SECRET_DB_PORT}:${SECRET_DB_PORT}"
    restart: unless-stopped
